# -*- coding: utf-8 -*-
"""project-1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VV7vKIYsMbzSG0S5EOLzeYM888wK4vBE

project-1:URL shortener
"""

pip install pyshorteners

import pyshorteners                 

url= input('Enter the url: ')      # taking input from user ,i.e longer url

def shorturl(url):                 # define a function def shorturl,which is going to take longer url and print shorten url
    s=pyshorteners.Shortener()     # we had created a object of pyshorteners
    print(s.tinyurl.short(url))    # we are taking longer url that we are taking as parameter
    
shorturl(url)